export interface Ad {
  id: number;
  title: string;
  price: number | null;
  category: string;
  subcategory: string;
  image: string;
  location: string;
  date: string;
  seller: string;
  sellerType: string;
  description: string;
  condition: string;
  brand: string;
  model: string;
  year: number | null;
  color: string;
  size: string | null;
  material: string | null;
  features: string[];
  shipping: string;
  warranty: boolean;
  rating: number;
  reviews: number;
  views: number;
  likes: number;
  negotiable: boolean;
  tags: string[];
  weight: number | null;
  dimensions: {
    length: number;
    width: number;
    height: number;
  } | null;
  inStock: number;
  paymentOptions: string[];
  returnPolicy: string;
  adType: string;
  verifiedSeller: boolean;
}

export const sampleData = {
  banner: {
    image:
      "https://images.unsplash.com/photo-1472851294608-062f824d29cc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    title: "Welcome to Our Marketplace",
    subtitle: "Discover amazing deals on unique items",
  },
  categories: [
    "All",
    "Electronics",
    "Fashion",
    "Home & Garden",
    "Sports & Outdoors",
    "Toys & Games",
    "Vehicles",
    "Books & Media",
    "Health & Beauty",
    "Pet Supplies",
    "Jewelry & Watches",
    "Musical Instruments",
    "Art & Collectibles",
    "Business & Industrial",
    "Food & Beverages",
  ],
  subcategories: {
    Electronics: [
      "Smartphones",
      "Laptops",
      "Cameras",
      "Audio",
      "Gaming",
      "Accessories",
    ],
    Fashion: [
      "Men's Clothing",
      "Women's Clothing",
      "Shoes",
      "Bags",
      "Accessories",
    ],
    "Home & Garden": ["Furniture", "Decor", "Kitchen", "Gardening", "Bedding"],
    "Sports & Outdoors": [
      "Fitness",
      "Camping",
      "Cycling",
      "Team Sports",
      "Water Sports",
    ],
    "Toys & Games": [
      "Board Games",
      "Puzzles",
      "Action Figures",
      "Dolls",
      "Educational Toys",
    ],
    Vehicles: ["Cars", "Motorcycles", "Boats", "RVs", "Parts & Accessories"],
    "Books & Media": ["Books", "Magazines", "Movies", "Music", "Video Games"],
    "Health & Beauty": [
      "Skincare",
      "Makeup",
      "Hair Care",
      "Fragrances",
      "Vitamins & Supplements",
    ],
    "Pet Supplies": [
      "Dog Supplies",
      "Cat Supplies",
      "Fish Supplies",
      "Bird Supplies",
      "Small Animal Supplies",
    ],
    "Jewelry & Watches": [
      "Necklaces",
      "Rings",
      "Earrings",
      "Bracelets",
      "Watches",
    ],
    "Musical Instruments": [
      "Guitars",
      "Pianos & Keyboards",
      "Drums",
      "DJ Equipment",
      "Brass & Woodwinds",
    ],
    "Art & Collectibles": [
      "Paintings",
      "Sculptures",
      "Prints",
      "Antiques",
      "Collectible Figurines",
    ],
    "Business & Industrial": [
      "Office Supplies",
      "Industrial Equipment",
      "Restaurant Supplies",
      "Retail",
      "Construction",
    ],
    "Food & Beverages": [
      "Gourmet Foods",
      "Beverages",
      "Snacks",
      "Organic & Natural",
      "Specialty Diets",
    ],
  },
  conditions: ["New", "Like New", "Good", "Fair", "Poor"],
  sellerTypes: ["Individual", "Business"],
  shippingOptions: ["Free", "Paid", "Pickup"],
  paymentOptions: ["Cash", "Card", "PayPal", "Crypto"],
  returnPolicies: ["No Returns", "14 Days", "30 Days", "60 Days"],
  adTypes: ["Standard", "Featured", "Urgent"],
  ads: [
    {
      id: 1,
      title: "Vintage Camera Collection",
      price: 1200,
      category: "Electronics",
      subcategory: "Cameras",
      image:
        "https://images.unsplash.com/photo-1452780212940-6f5c0d14d848?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80",
      location: "Downtown",
      date: "2023-06-15",
      seller: "RetroCollector",
      sellerType: "individual",
      description:
        "A set of beautifully preserved vintage cameras from various eras.",
      condition: "good",
      brand: "Various",
      model: "Mixed",
      year: null,
      color: "Mixed",
      size: null,
      material: "Metal",
      features: ["Manual focus", "Film compatible", "Collectible"],
      shipping: "paid",
      warranty: false,
      rating: 4.8,
      reviews: 15,
      views: 230,
      likes: 45,
      negotiable: true,
      tags: ["vintage", "camera", "collection", "photography"],
      weight: 5000,
      dimensions: { length: 50, width: 30, height: 20 },
      inStock: 1,
      paymentOptions: ["cash", "paypal"],
      returnPolicy: "no-returns",
      adType: "featured",
      verifiedSeller: true,
    },
    {
      id: 2,
      title: "Designer Handbag",
      price: 850,
      category: "Fashion",
      subcategory: "Bags",
      image:
        "https://images.unsplash.com/photo-1584917865442-de89df76afd3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      location: "Fashion District",
      date: "2023-06-14",
      seller: "LuxuryFinds",
      sellerType: "business",
      description:
        "Authentic designer handbag, gently used and in excellent condition.",
      condition: "like-new",
      brand: "Gucci",
      model: "Dionysus",
      year: 2022,
      color: "Black",
      size: "Medium",
      material: "Leather",
      features: ["Adjustable strap", "Interior pockets", "Designer logo"],
      shipping: "free",
      warranty: false,
      rating: 4.9,
      reviews: 28,
      views: 512,
      likes: 89,
      negotiable: false,
      tags: ["designer", "handbag", "luxury", "fashion"],
      weight: 1000,
      dimensions: { length: 30, width: 10, height: 20 },
      inStock: 1,
      paymentOptions: ["card", "paypal"],
      returnPolicy: "14-days",
      adType: "featured",
      verifiedSeller: true,
    },
    {
      id: 3,
      title: "Mountain Bike",
      price: 599,
      category: "Sports & Outdoors",
      subcategory: "Bicycles",
      image:
        "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2068&q=80",
      location: "Suburbs",
      date: "2023-06-13",
      seller: "BikeEnthusiast",
      sellerType: "individual",
      description:
        "High-performance mountain bike, perfect for trails and rough terrain.",
      condition: "good",
      brand: "Trek",
      model: "Fuel EX 7",
      year: 2021,
      color: "Red",
      size: "Large",
      material: "Aluminum",
      features: ["Full suspension", "Disc brakes", '27.5" wheels'],
      shipping: "pickup",
      warranty: true,
      rating: 4.7,
      reviews: 12,
      views: 180,
      likes: 34,
      negotiable: true,
      tags: ["mountain bike", "outdoor", "sports", "cycling"],
      weight: 14000,
      dimensions: { length: 180, width: 60, height: 100 },
      inStock: 1,
      paymentOptions: ["cash", "card"],
      returnPolicy: "30-days",
      adType: "standard",
      verifiedSeller: false,
    },
    {
      id: 4,
      title: "Antique Wooden Desk",
      price: 450,
      category: "Home & Garden",
      subcategory: "Furniture",
      image:
        "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2069&q=80",
      location: "City Center",
      date: "2023-06-12",
      seller: "VintageHome",
      sellerType: "business",
      description:
        "Beautiful antique wooden desk with intricate carvings and ample storage.",
      condition: "fair",
      brand: "Unknown",
      model: "Victorian Style",
      year: 1920,
      color: "Dark Brown",
      size: null,
      material: "Oak",
      features: ["Multiple drawers", "Carved details", "Brass hardware"],
      shipping: "paid",
      warranty: false,
      rating: 4.5,
      reviews: 8,
      views: 120,
      likes: 22,
      negotiable: true,
      tags: ["antique", "furniture", "desk", "wooden"],
      weight: 50000,
      dimensions: { length: 120, width: 60, height: 75 },
      inStock: 1,
      paymentOptions: ["cash", "card", "paypal"],
      returnPolicy: "no-returns",
      adType: "standard",
      verifiedSeller: true,
    },
    {
      id: 5,
      title: "iPhone 12 Pro",
      price: 699,
      category: "Electronics",
      subcategory: "Smartphones",
      image:
        "https://images.unsplash.com/photo-1603891128711-11b4b03bb138?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      location: "Tech Hub",
      date: "2023-06-11",
      seller: "GadgetPro",
      sellerType: "business",
      description:
        "Slightly used iPhone 12 Pro in excellent condition with all accessories.",
      condition: "like-new",
      brand: "Apple",
      model: "iPhone 12 Pro",
      year: 2020,
      color: "Pacific Blue",
      size: "6.1 inch",
      material: "Glass and stainless steel",
      features: ["5G", "A14 Bionic chip", "Pro camera system"],
      shipping: "free",
      warranty: true,
      rating: 4.9,
      reviews: 45,
      views: 890,
      likes: 156,
      negotiable: false,
      tags: ["iphone", "smartphone", "apple", "mobile"],
      weight: 189,
      dimensions: { length: 146.7, width: 71.5, height: 7.4 },
      inStock: 3,
      paymentOptions: ["card", "paypal"],
      returnPolicy: "14-days",
      adType: "featured",
      verifiedSeller: true,
    },
    {
      id: 6,
      title: "Vintage Vinyl Records Collection",
      price: 300,
      category: "Books & Media",
      subcategory: "Music",
      image:
        "https://images.unsplash.com/photo-1603048588665-791ca8aea617?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1964&q=80",
      location: "Music District",
      date: "2023-06-10",
      seller: "VinylEnthusiast",
      sellerType: "individual",
      description:
        "A collection of 50 vintage vinyl records from various artists and genres.",
      condition: "good",
      brand: "Various",
      model: "Mixed",
      year: null,
      color: "Mixed",
      size: "12 inch",
      material: "Vinyl",
      features: ["Rare editions", "Original sleeves", "Mixed genres"],
      shipping: "paid",
      warranty: false,
      rating: 4.7,
      reviews: 18,
      views: 250,
      likes: 67,
      negotiable: true,
      tags: ["vinyl", "records", "music", "vintage"],
      weight: 10000,
      dimensions: { length: 31, width: 31, height: 40 },
      inStock: 1,
      paymentOptions: ["cash", "paypal"],
      returnPolicy: "no-returns",
      adType: "standard",
      verifiedSeller: false,
    },
    {
      id: 7,
      title: "Professional DSLR Camera",
      price: 1499,
      category: "Electronics",
      subcategory: "Cameras",
      image:
        "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1964&q=80",
      location: "Downtown",
      date: "2023-06-09",
      seller: "PhotoPro",
      sellerType: "business",
      description: "High-end DSLR camera with multiple lenses and accessories.",
      condition: "new",
      brand: "Canon",
      model: "EOS 5D Mark IV",
      year: 2023,
      color: "Black",
      size: null,
      material: "Magnesium alloy",
      features: ["30.4MP full-frame sensor", "4K video", "61-point AF"],
      shipping: "free",
      warranty: true,
      rating: 5.0,
      reviews: 32,
      views: 780,
      likes: 201,
      negotiable: false,
      tags: ["camera", "dslr", "photography", "professional"],
      weight: 800,
      dimensions: { length: 15, width: 11.6, height: 7.6 },
      inStock: 5,
      paymentOptions: ["card", "paypal"],
      returnPolicy: "30-days",
      adType: "featured",
      verifiedSeller: true,
    },
    {
      id: 8,
      title: "Handmade Ceramic Vase",
      price: 80,
      category: "Home & Garden",
      subcategory: "Decor",
      image:
        "https://images.unsplash.com/photo-1578500351865-d6c3706f46bc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2127&q=80",
      location: "Artisan Quarter",
      date: "2023-06-08",
      seller: "CeramicArtist",
      sellerType: "individual",
      description:
        "Unique handmade ceramic vase with intricate patterns and glazing.",
      condition: "new",
      brand: "Handmade",
      model: "One of a kind",
      year: 2023,
      color: "Blue and white",
      size: "Medium",
      material: "Ceramic",
      features: ["Hand-painted", "Glazed finish", "Unique design"],
      shipping: "paid",
      warranty: false,
      rating: 4.8,
      reviews: 9,
      views: 150,
      likes: 38,
      negotiable: true,
      tags: ["vase", "ceramic", "handmade", "decor"],
      weight: 1000,
      dimensions: { length: 20, width: 20, height: 30 },
      inStock: 1,
      paymentOptions: ["cash", "card"],
      returnPolicy: "no-returns",
      adType: "standard",
      verifiedSeller: false,
    },
    {
      id: 9,
      title: "Vintage Leather Jacket",
      price: 200,
      category: "Fashion",
      subcategory: "Men's Clothing",
      image:
        "https://images.unsplash.com/photo-1551028719-00167b16eac5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1935&q=80",
      location: "Fashion District",
      date: "2023-06-07",
      seller: "VintageClothier",
      sellerType: "business",
      description:
        "Authentic vintage leather jacket from the 1970s, well-maintained.",
      condition: "good",
      brand: "Unknown",
      model: "Biker style",
      year: 1970,
      color: "Brown",
      size: "Medium",
      material: "Leather",
      features: ["Zip front", "Multiple pockets", "Quilted lining"],
      shipping: "paid",
      warranty: false,
      rating: 4.6,
      reviews: 14,
      views: 320,
      likes: 87,
      negotiable: true,
      tags: ["vintage", "leather", "jacket", "fashion"],
      weight: 2000,
      dimensions: null,
      inStock: 1,
      paymentOptions: ["cash", "card", "paypal"],
      returnPolicy: "no-returns",
      adType: "standard",
      verifiedSeller: true,
    },
    {
      id: 10,
      title: "Electric Guitar",
      price: 550,
      category: "Musical Instruments",
      subcategory: "Guitars",
      image:
        "https://images.unsplash.com/photo-1550985616-10810253b84d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2097&q=80",
      location: "Music Quarter",
      date: "2023-06-06",
      seller: "GuitarLover",
      sellerType: "individual",
      description:
        "Fender Stratocaster electric guitar in excellent condition with case.",
      condition: "like-new",
      brand: "Fender",
      model: "Stratocaster",
      year: 2021,
      color: "Sunburst",
      size: "Full size",
      material: "Alder body, Maple neck",
      features: ["3 single-coil pickups", "Tremolo bridge", "22 frets"],
      shipping: "paid",
      warranty: false,
      rating: 4.9,
      reviews: 22,
      views: 450,
      likes: 110,
      negotiable: false,
      tags: ["guitar", "electric", "fender", "music"],
      weight: 3600,
      dimensions: { length: 100, width: 30, height: 10 },
      inStock: 1,
      paymentOptions: ["cash", "card", "paypal"],
      returnPolicy: "14-days",
      adType: "featured",
      verifiedSeller: false,
    },
    {
      id: 11,
      title: "Vintage Typewriter",
      price: 150,
      category: "Art & Collectibles",
      subcategory: "Antiques",
      image:
        "https://images.unsplash.com/photo-1558392204-ac78741f4abf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      location: "Antique District",
      date: "2023-06-05",
      seller: "RetroCollector",
      sellerType: "individual",
      description:
        "Fully functional vintage typewriter from the 1950s, great for collectors.",
      condition: "fair",
      brand: "Remington",
      model: "Quiet-Riter",
      year: 1955,
      color: "Green",
      size: null,
      material: "Metal",
      features: ["QWERTY keyboard", "Portable", "Original case"],
      shipping: "paid",
      warranty: false,
      rating: 4.5,
      reviews: 7,
      views: 180,
      likes: 42,
      negotiable: true,
      tags: ["typewriter", "vintage", "antique", "collectible"],
      weight: 5000,
      dimensions: { length: 35, width: 30, height: 15 },
      inStock: 1,
      paymentOptions: ["cash", "paypal"],
      returnPolicy: "no-returns",
      adType: "standard",
      verifiedSeller: false,
    },
    {
      id: 12,
      title: "Smart Home Security System",
      price: 299,
      category: "Electronics",
      subcategory: "Smart Home",
      image:
        "https://images.unsplash.com/photo-1558002038-1055907df827?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      location: "Tech Hub",
      date: "2023-06-04",
      seller: "SmartHomePro",
      sellerType: "business",
      description:
        "Complete smart home security system with cameras, sensors, and mobile app control.",
      condition: "new",
      brand: "Ring",
      model: "Alarm Security Kit",
      year: 2023,
      color: "White",
      size: null,
      material: "Plastic",
      features: ["Wi-Fi connected", "Mobile app control", "Motion detection"],
      shipping: "free",
      warranty: true,
      rating: 4.8,
      reviews: 56,
      views: 890,
      likes: 234,
      negotiable: false,
      tags: ["smart home", "security", "camera", "sensors"],
      weight: 2500,
      dimensions: { length: 30, width: 25, height: 20 },
      inStock: 10,
      paymentOptions: ["card", "paypal"],
      returnPolicy: "30-days",
      adType: "featured",
      verifiedSeller: true,
    },
    {
      id: 13,
      title: "Handmade Quilt",
      price: 180,
      category: "Home & Garden",
      subcategory: "Bedding",
      image:
        "https://images.unsplash.com/photo-1570362685387-3cf5499c3fdc?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8SGFuZG1hZGUlMjBRdWlsdHxlbnwwfHwwfHx8MA%3D%3D",
      location: "Craft Village",
      date: "2023-06-03",
      seller: "QuiltMaster",
      sellerType: "individual",
      description:
        "Beautiful handmade quilt with intricate patchwork design, perfect for a queen-size bed.",
      condition: "new",
      brand: "Handmade",
      model: "One of a kind",
      year: 2023,
      color: "Multicolor",
      size: "Queen",
      material: "Cotton",
      features: ["Hand-stitched", "Reversible", "Machine washable"],
      shipping: "paid",
      warranty: false,
      rating: 5.0,
      reviews: 12,
      views: 210,
      likes: 78,
      negotiable: true,
      tags: ["quilt", "handmade", "bedding", "home decor"],
      weight: 3000,
      dimensions: { length: 230, width: 210, height: 2 },
      inStock: 1,
      paymentOptions: ["cash", "card", "paypal"],
      returnPolicy: "no-returns",
      adType: "standard",
      verifiedSeller: false,
    },
    {
      id: 14,
      title: "Vintage Rolex Watch",
      price: 8500,
      category: "Jewelry & Watches",
      subcategory: "Watches",
      image:
        "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      location: "Luxury District",
      date: "2023-06-02",
      seller: "LuxuryTimepieces",
      sellerType: "business",
      description:
        "Authentic vintage Rolex Datejust, excellent condition with original box and papers.",
      condition: "like-new",
      brand: "Rolex",
      model: "Datejust",
      year: 1985,
      color: "Silver and Gold",
      size: "36mm",
      material: "Stainless steel and 18k gold",
      features: ["Automatic movement", "Date function", "Jubilee bracelet"],
      shipping: "free",
      warranty: true,
      rating: 4.9,
      reviews: 28,
      views: 1200,
      likes: 456,
      negotiable: false,
      tags: ["watch", "rolex", "luxury", "vintage"],
      weight: 150,
      dimensions: { length: 5, width: 5, height: 2 },
      inStock: 1,
      paymentOptions: ["card", "bank transfer"],
      returnPolicy: "14-days",
      adType: "featured",
      verifiedSeller: true,
    },
    {
      id: 15,
      title: "Vintage Comic Book Collection",
      price: 5000,
      category: "Books & Media",
      subcategory: "Comics",
      image:
        "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      location: "Comic Book Alley",
      date: "2023-06-01",
      seller: "ComicCollector",
      sellerType: "individual",
      description:
        "Rare collection of vintage Marvel and DC comics from the 1960s and 1970s.",
      condition: "good",
      brand: "Marvel, DC",
      model: "Various",
      year: null,
      color: "Mixed",
      size: null,
      material: "Paper",
      features: ["First editions", "Rare issues", "Well-preserved"],
      shipping: "paid",
      warranty: false,
      rating: 4.8,
      reviews: 15,
      views: 680,
      likes: 210,
      negotiable: true,
      tags: ["comics", "vintage", "collection", "marvel", "dc"],
      weight: 10000,
      dimensions: { length: 40, width: 30, height: 20 },
      inStock: 1,
      paymentOptions: ["cash", "bank transfer"],
      returnPolicy: "no-returns",
      adType: "featured",
      verifiedSeller: false,
    },
    {
      id: 16,
      title: "Antique Writing Desk",
      price: 1200,
      category: "Home & Garden",
      subcategory: "Furniture",
      image:
        "https://images.unsplash.com/photo-1517705185975-b3301eaa9c8e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      location: "Antique District",
      date: "2023-05-31",
      seller: "AntiqueTreasures",
      sellerType: "business",
      description:
        "Beautifully restored 19th-century mahogany writing desk with leather top.",
      condition: "good",
      brand: "Unknown",
      model: "Victorian",
      year: 1880,
      color: "Dark Brown",
      size: null,
      material: "Mahogany, Leather",
      features: [
        "Multiple drawers",
        "Leather writing surface",
        "Brass hardware",
      ],
      shipping: "paid",
      warranty: false,
      rating: 4.7,
      reviews: 9,
      views: 320,
      likes: 87,
      negotiable: true,
      tags: ["antique", "desk", "furniture", "vintage"],
      weight: 50000,
      dimensions: { length: 120, width: 70, height: 80 },
      inStock: 1,
      paymentOptions: ["cash", "card", "bank transfer"],
      returnPolicy: "no-returns",
      adType: "standard",
      verifiedSeller: true,
    },
    {
      id: 17,
      title: "Professional DJ Equipment Set",
      price: 3500,
      category: "Musical Instruments",
      subcategory: "DJ Equipment",
      image:
        "https://images.unsplash.com/photo-1571935441005-07ac18f4bf23?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      location: "Music Quarter",
      date: "2023-05-30",
      seller: "DJMaster",
      sellerType: "business",
      description:
        "Complete professional DJ setup including turntables, mixer, and speakers.",
      condition: "like-new",
      brand: "Pioneer",
      model: "Various",
      year: 2022,
      color: "Black",
      size: null,
      material: "Mixed",
      features: ["High-quality audio", "Multiple inputs", "Effects controls"],
      shipping: "free",
      warranty: true,
      rating: 4.9,
      reviews: 34,
      views: 890,
      likes: 267,
      negotiable: false,
      tags: ["dj", "music", "equipment", "professional"],
      weight: 50000,
      dimensions: { length: 100, width: 80, height: 120 },
      inStock: 2,
      paymentOptions: ["card", "paypal", "financing"],
      returnPolicy: "30-days",
      adType: "featured",
      verifiedSeller: true,
    },
    {
      id: 18,
      title: "Vintage Polaroid Camera",
      price: 75,
      category: "Electronics",
      subcategory: "Cameras",
      image:
        "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      location: "Retro District",
      date: "2023-05-29",
      seller: "RetroGadgets",
      sellerType: "individual",
      description:
        "Fully functional vintage Polaroid camera from the 1980s, great for instant photography enthusiasts.",
      condition: "fair",
      brand: "Polaroid",
      model: "Sun 600",
      year: 1981,
      color: "Rainbow",
      size: null,
      material: "Plastic",
      features: ["Instant photos", "Built-in flash", "Folding design"],
      shipping: "paid",
      warranty: false,
      rating: 4.3,
      reviews: 11,
      views: 240,
      likes: 56,
      negotiable: true,
      tags: ["camera", "polaroid", "vintage", "photography"],
      weight: 700,
      dimensions: { length: 15, width: 10, height: 10 },
      inStock: 1,
      paymentOptions: ["cash", "paypal"],
      returnPolicy: "no-returns",
      adType: "standard",
      verifiedSeller: false,
    },
    {
      id: 19,
      title: "Handcrafted Leather Briefcase",
      price: 350,
      category: "Fashion",
      subcategory: "Bags",
      image:
        "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2069&q=80",
      location: "Artisan Quarter",
      date: "2023-05-28",
      seller: "LeatherCraftsman",
      sellerType: "business",
      description:
        "Handmade full-grain leather briefcase, perfect for professionals and daily use.",
      condition: "new",
      brand: "Handmade",
      model: "Executive",
      year: 2023,
      color: "Brown",
      size: "15 inch laptop",
      material: "Full-grain leather",
      features: ["Multiple compartments", "Adjustable strap", "Brass hardware"],
      shipping: "free",
      warranty: true,
      rating: 5.0,
      reviews: 23,
      views: 560,
      likes: 178,
      negotiable: false,
      tags: ["briefcase", "leather", "handmade", "fashion"],
      weight: 1500,
      dimensions: { length: 40, width: 30, height: 15 },
      inStock: 5,
      paymentOptions: ["card", "paypal"],
      returnPolicy: "30-days",
      adType: "featured",
      verifiedSeller: true,
    },
    {
      id: 20,
      title: "Vintage Board Game Collection",
      price: 200,
      category: "Toys & Games",
      subcategory: "Board Games",
      image:
        "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2071&q=80",
      location: "Game Store",
      date: "2023-05-27",
      seller: "BoardGameEnthusiast",
      sellerType: "individual",
      description:
        "Collection of 10 classic board games from the 1960s and 1970s, all in good condition.",
      condition: "good",
      brand: "Various",
      model: "Mixed",
      year: null,
      color: "Mixed",
      size: null,
      material: "Cardboard, Plastic",
      features: ["Classic games", "Vintage editions", "Family-friendly"],
      shipping: "paid",
      warranty: false,
      rating: 4.6,
      reviews: 8,
      views: 190,
      likes: 45,
      negotiable: true,
      tags: ["board games", "vintage", "collection", "family"],
      weight: 8000,
      dimensions: { length: 50, width: 40, height: 30 },
      inStock: 1,
      paymentOptions: ["cash", "paypal"],
      returnPolicy: "no-returns",
      adType: "standard",
      verifiedSeller: false,
    },
  ],
};

export function getAdById(id: number): Ad | undefined {
  return sampleData.ads.find((ad) => ad.id === id);
}
