"use client";
import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Bell, Calendar, Check, ChevronDown, Circle, Filter, MoreHorizontal, Plus, Search, Sparkles, X } from "lucide-react";

type Task={id:number;title:string;note:string;tag:string;due:string;people:string[];color:string};
type Column={id:string;name:string;color:string;tasks:Task[]};
const initial:Column[]=[
{id:"todo",name:"To do",color:"#8e8e93",tasks:[{id:1,title:"Define launch strategy",note:"Outline audience, channels and core message.",tag:"Strategy",due:"Sep 16",people:["/avatar-40-01.jpg","/avatar-40-03.jpg"],color:"#af52de"},{id:2,title:"Competitive research",note:"Review positioning and onboarding flows.",tag:"Research",due:"Sep 18",people:["/avatar-40-04.jpg"],color:"#0071e3"},{id:3,title:"Finalize product copy",note:"Polish the primary landing page narrative.",tag:"Content",due:"Sep 20",people:["/avatar-40-02.jpg"],color:"#ff9f0a"}]},
{id:"progress",name:"In progress",color:"#0071e3",tasks:[{id:4,title:"Design system audit",note:"Consolidate components and interaction states.",tag:"Design",due:"Today",people:["/avatar-40-03.jpg","/avatar-40-02.jpg"],color:"#ff375f"},{id:5,title:"Build analytics view",note:"Implement responsive chart and KPI cards.",tag:"Engineering",due:"Sep 17",people:["/avatar-40-01.jpg"],color:"#34c759"}]},
{id:"review",name:"In review",color:"#ff9f0a",tasks:[{id:6,title:"Motion prototypes",note:"Validate spring timing and reduced motion.",tag:"Design",due:"Tomorrow",people:["/avatar-40-04.jpg"],color:"#af52de"}]},
{id:"done",name:"Completed",color:"#34c759",tasks:[{id:7,title:"Kickoff workshop",note:"Align the team on goals and ownership.",tag:"Planning",due:"Sep 10",people:["/avatar-40-02.jpg","/avatar-40-01.jpg"],color:"#0071e3"},{id:8,title:"Project brief",note:"Document scope, metrics and milestones.",tag:"Strategy",due:"Sep 11",people:["/avatar-40-03.jpg"],color:"#34c759"}]}
];
export default function Kanban(){const [columns,setColumns]=useState(initial);const [query,setQuery]=useState("");const [modal,setModal]=useState<string|null>(null);const [title,setTitle]=useState("");const visible=useMemo(()=>columns.map(c=>({...c,tasks:c.tasks.filter(t=>t.title.toLowerCase().includes(query.toLowerCase()))})),[columns,query]);function add(){if(!title.trim()||!modal)return;setColumns(cs=>cs.map(c=>c.id===modal?{...c,tasks:[...c.tasks,{id:Date.now(),title,note:"New task ready for details.",tag:"New",due:"No date",people:[],color:"#0071e3"}]}:c));setTitle("");setModal(null)}
return <div className="apple-page"><header className="apple-topbar"><div className="flex items-center gap-2 text-sm font-semibold"><span className="h-2.5 w-2.5 rounded-full bg-[#af52de]"/>Projects</div><div className="flex items-center gap-2"><button className="apple-icon-button"><Search size={17}/></button><button className="apple-icon-button relative"><Bell size={17}/><span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-red-500 ring-2 ring-white dark:ring-zinc-900"/></button><img src="/profile.jpg" alt="Profile" className="h-9 w-9 rounded-full object-cover"/></div></header>
<main className="mx-auto max-w-[1550px] apple-enter"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-sm text-muted-foreground">Workspace <span>/</span> Product launch <ChevronDown size={14}/></div><h1 className="apple-title mt-1">Product launch</h1><p className="apple-subtitle">Everything the team needs to ship beautifully.</p></div><div className="flex items-center gap-2"><div className="hidden items-center -space-x-2 sm:flex">{[1,2,3,4].map(n=><img key={n} src={`/avatar-40-0${n}.jpg`} alt="" className="h-8 w-8 rounded-full border-2 border-[#f5f5f7] object-cover dark:border-[#09090b]"/>)}<span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#f5f5f7] bg-zinc-200 text-[10px] font-semibold dark:border-[#09090b] dark:bg-zinc-700">+3</span></div><button className="apple-icon-button w-auto gap-2 px-4"><Filter size={15}/> Filter</button><button className="apple-button" onClick={()=>setModal("todo")}><Plus size={16}/> Add task</button></div></div>
<div className="mt-6 flex items-center gap-3"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-2.5 text-muted-foreground" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this board" className="h-9 w-full rounded-xl border-0 bg-black/[.055] pl-9 pr-3 text-sm outline-none ring-[#0071e3] focus:ring-2 dark:bg-white/[.08]"/></div><span className="hidden text-xs text-muted-foreground sm:block">{columns.reduce((n,c)=>n+c.tasks.length,0)} tasks · Updated just now</span></div>
<div className="mt-5 grid items-start gap-3 lg:grid-cols-4">{visible.map((col,ci)=><motion.section initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:ci*.07}} key={col.id} className="rounded-[24px] bg-black/[.035] p-2 dark:bg-white/[.035]"><div className="flex items-center justify-between px-2 py-2"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{background:col.color}}/><h2 className="text-sm font-semibold">{col.name}</h2><span className="text-xs text-muted-foreground">{col.tasks.length}</span></div><button className="text-muted-foreground"><MoreHorizontal size={17}/></button></div><div className="space-y-2 min-h-24"><AnimatePresence>{col.tasks.map((task,ti)=><motion.article layout initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.95}} whileHover={{y:-2}} transition={{duration:.2}} key={task.id} className="apple-card cursor-pointer p-4"><div className="flex items-start justify-between gap-3"><span className="rounded-full px-2 py-1 text-[10px] font-semibold" style={{color:task.color,background:`${task.color}16`}}>{task.tag}</span><button className="text-muted-foreground"><MoreHorizontal size={15}/></button></div><h3 className="mt-3 text-[14px] font-semibold leading-tight">{task.title}</h3><p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">{task.note}</p><div className="mt-4 flex items-center justify-between"><span className={`flex items-center gap-1 text-[11px] ${task.due==="Today"?"text-red-500":"text-muted-foreground"}`}><Calendar size={12}/>{task.due}</span><div className="flex -space-x-1.5">{task.people.map((p,i)=><img src={p} key={i} alt="" className="h-6 w-6 rounded-full border-2 border-white object-cover dark:border-[#161617]"/>)}{col.id==="done"&&<span className="grid h-6 w-6 place-items-center rounded-full bg-green-500 text-white"><Check size={12}/></span>}</div></div></motion.article>)}</AnimatePresence></div><button onClick={()=>setModal(col.id)} className="mt-2 flex w-full items-center gap-2 rounded-2xl px-3 py-2.5 text-xs font-medium text-muted-foreground transition hover:bg-black/5 hover:text-foreground dark:hover:bg-white/5"><Plus size={14}/> Add task</button></motion.section>)}</div></main>
<AnimatePresence>{modal&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/20 p-4 backdrop-blur-sm" onMouseDown={()=>setModal(null)}><motion.div initial={{opacity:0,scale:.94,y:15}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.96}} transition={{type:"spring",stiffness:400,damping:30}} onMouseDown={e=>e.stopPropagation()} className="apple-card w-full max-w-md p-6"><div className="flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-blue-500/10 text-[#0071e3]"><Sparkles size={19}/></div><button onClick={()=>setModal(null)} className="apple-icon-button"><X size={16}/></button></div><h2 className="mt-5 text-xl font-semibold tracking-tight">Create a new task</h2><p className="mt-1 text-sm text-muted-foreground">Add it to the board now. You can refine the details later.</p><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="What needs to be done?" className="mt-5 h-12 w-full rounded-xl bg-black/5 px-4 text-sm outline-none ring-[#0071e3] focus:ring-2 dark:bg-white/10"/><div className="mt-5 flex justify-end gap-2"><button className="apple-icon-button w-auto px-4" onClick={()=>setModal(null)}>Cancel</button><button className="apple-button" onClick={add}>Create task</button></div></motion.div></div>}</AnimatePresence></div>}
