"use client";
import { FormEvent, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Bell, Camera, ChevronLeft, Info, Mic, MoreHorizontal, Paperclip, Phone, Search, Send, Smile, Video } from "lucide-react";
const chats=[
{name:"Sofia Davis",text:"That looks absolutely perfect!",time:"10:42",avatar:"/avatar-80-01.jpg",online:true,unread:2},
{name:"Jackson Lee",text:"I shared the latest prototype.",time:"9:18",avatar:"/avatar-80-02.jpg",online:true,unread:0},
{name:"Design Team",text:"Olivia: Let’s ship it 🚀",time:"Tue",avatar:"/avatar-80-03.jpg",online:false,unread:4},
{name:"Isabella Nguyen",text:"Can we catch up tomorrow?",time:"Mon",avatar:"/avatar-80-04.jpg",online:false,unread:0},
{name:"William Kim",text:"Thanks for the thoughtful notes.",time:"Sun",avatar:"/avatar-80-05.jpg",online:true,unread:0},
];
type Msg={id:number;mine:boolean;text:string;time:string};
const seed:Msg[]=[{id:1,mine:false,text:"Hey Alex! I just reviewed the new dashboard direction.",time:"10:36"},{id:2,mine:false,text:"The hierarchy feels so much clearer now. Really beautiful work.",time:"10:37"},{id:3,mine:true,text:"Thank you! I wanted it to feel focused and effortless — nothing competing for attention.",time:"10:39"},{id:4,mine:true,text:"I’ve also refined the motion so every transition feels more natural.",time:"10:40"},{id:5,mine:false,text:"That looks absolutely perfect! ✨",time:"10:42"}];
export default function Messages(){const [active,setActive]=useState(0);const [messages,setMessages]=useState(seed);const [value,setValue]=useState("");const [mobileChat,setMobileChat]=useState(false);function send(e:FormEvent){e.preventDefault();if(!value.trim())return;setMessages(m=>[...m,{id:Date.now(),mine:true,text:value.trim(),time:"Now"}]);setValue("")}
const person=chats[active];return <div className="apple-page h-screen overflow-hidden pb-4"><header className="apple-topbar mb-4"><div className="flex items-center gap-2 text-sm font-semibold"><span className="h-2.5 w-2.5 rounded-full bg-[#0071e3]"/>Messages</div><div className="flex items-center gap-2"><button className="apple-icon-button"><Bell size={17}/></button><img src="/profile.jpg" alt="Profile" className="h-9 w-9 rounded-full object-cover"/></div></header><main className="apple-card mx-auto flex h-[calc(100vh-100px)] max-w-[1450px] overflow-hidden apple-enter">
<aside className={`${mobileChat?"hidden":"flex"} w-full shrink-0 flex-col border-r border-black/[.06] md:flex md:w-[330px] dark:border-white/[.07]`}><div className="p-5 pb-3"><div className="flex items-center justify-between"><h1 className="text-2xl font-semibold tracking-tight">Messages</h1><button className="apple-icon-button"><MoreHorizontal size={17}/></button></div><label className="relative mt-4 block"><Search className="absolute left-3 top-2.5 text-muted-foreground" size={16}/><input placeholder="Search" className="h-9 w-full rounded-xl bg-black/[.055] pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-[#0071e3] dark:bg-white/[.08]"/></label></div><div className="overflow-y-auto px-2 pb-3">{chats.map((c,i)=><button key={c.name} onClick={()=>{setActive(i);setMobileChat(true)}} className={`flex w-full items-center gap-3 rounded-2xl p-3 text-left transition ${active===i?"bg-[#0071e3] text-white":"hover:bg-black/[.04] dark:hover:bg-white/[.05]"}`}><div className="relative"><img src={c.avatar} alt="" className="h-12 w-12 rounded-full object-cover"/>{c.online&&<span className={`absolute bottom-0 right-0 h-3.5 w-3.5 rounded-full border-2 ${active===i?"border-[#0071e3]":"border-white dark:border-[#161617]"} bg-[#34c759]`}/>}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><b className="truncate text-sm">{c.name}</b><span className={`text-[11px] ${active===i?"text-white/70":"text-muted-foreground"}`}>{c.time}</span></div><div className="mt-1 flex items-center justify-between gap-2"><p className={`truncate text-xs ${active===i?"text-white/75":"text-muted-foreground"}`}>{c.text}</p>{c.unread>0&&<span className={`grid h-5 min-w-5 place-items-center rounded-full px-1 text-[10px] font-bold ${active===i?"bg-white text-[#0071e3]":"bg-[#0071e3] text-white"}`}>{c.unread}</span>}</div></div></button>)}</div></aside>
<section className={`${mobileChat?"flex":"hidden"} min-w-0 flex-1 flex-col md:flex`}><div className="flex h-[68px] items-center justify-between border-b border-black/[.06] px-4 sm:px-5 dark:border-white/[.07]"><div className="flex items-center gap-3"><button onClick={()=>setMobileChat(false)} className="apple-icon-button md:hidden"><ChevronLeft size={18}/></button><div className="relative"><img src={person.avatar} className="h-10 w-10 rounded-full object-cover" alt=""/><span className="absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-white bg-[#34c759] dark:border-[#161617]"/></div><div><h2 className="text-sm font-semibold">{person.name}</h2><p className="text-[11px] text-[#248a3d]">Online now</p></div></div><div className="flex gap-1"><button className="apple-icon-button"><Phone size={16}/></button><button className="apple-icon-button"><Video size={17}/></button><button className="apple-icon-button hidden sm:inline-flex"><Info size={17}/></button></div></div>
<div className="flex-1 overflow-y-auto px-4 py-6 sm:px-8"><div className="mx-auto max-w-2xl"><div className="mb-7 text-center"><img src={person.avatar} alt="" className="mx-auto h-16 w-16 rounded-full object-cover"/><h3 className="mt-2 font-semibold">{person.name}</h3><p className="text-xs text-muted-foreground">You’re connected on Pexlle</p></div><div className="mb-5 flex items-center gap-3 text-[10px] uppercase tracking-wider text-muted-foreground"><span className="h-px flex-1 bg-black/5 dark:bg-white/5"/>Today<span className="h-px flex-1 bg-black/5 dark:bg-white/5"/></div><AnimatePresence initial={false}>{messages.map((m,i)=><motion.div initial={{opacity:0,y:8,scale:.97}} animate={{opacity:1,y:0,scale:1}} key={m.id} className={`mb-2 flex ${m.mine?"justify-end":"justify-start"}`}><div className="max-w-[82%]"><div className={`rounded-[20px] px-4 py-2.5 text-[14px] leading-relaxed ${m.mine?"rounded-br-md bg-[#0071e3] text-white":"rounded-bl-md bg-black/[.06] dark:bg-white/[.09]"}`}>{m.text}</div>{(i===messages.length-1||messages[i+1]?.mine!==m.mine)&&<p className={`mt-1 px-1 text-[10px] text-muted-foreground ${m.mine?"text-right":""}`}>{m.time}{m.mine&&" · Delivered"}</p>}</div></motion.div>)}</AnimatePresence></div></div>
<form onSubmit={send} className="p-3 sm:p-5"><div className="mx-auto flex max-w-2xl items-end gap-2"><button type="button" className="apple-icon-button shrink-0"><PlusIcon/></button><div className="flex min-h-11 flex-1 items-center rounded-[22px] border border-black/10 bg-white px-3 shadow-sm focus-within:ring-2 focus-within:ring-[#0071e3] dark:border-white/10 dark:bg-white/[.07]"><input value={value} onChange={e=>setValue(e.target.value)} placeholder="iMessage" className="h-10 min-w-0 flex-1 bg-transparent text-sm outline-none"/><button type="button" className="p-2 text-muted-foreground"><Smile size={18}/></button>{value?<button className="grid h-7 w-7 place-items-center rounded-full bg-[#0071e3] text-white"><Send size={14}/></button>:<button type="button" className="p-1 text-muted-foreground"><Mic size={18}/></button>}</div></div></form></section></main></div>}
function PlusIcon(){return <Paperclip size={17}/>}
